# Generated by Django 3.1.1 on 2020-11-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_library', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
