# Generated by Django 3.1.1 on 2020-09-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/image-not-found.jpg', upload_to='images/'),
        ),
    ]
