# Generated by Django 5.1.5 on 2025-02-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_auto_20200906_0204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
